EASY_ICONS = {
    # the function that will be used to get the icon based on user settings
    "default_renderer": "provider",
    # default attributes applied to all icons
    "attrs": {
        # "height": "1em",
        # "fill": "currentColor",
    },
    # maps aliases to icon names
    "aliases": {
        "administration": "fas fa-toolbox",
        "activity": "activity.svg",
        "angle-left": "fas fa-angle-left",
        "angle-right": "fas fa-angle-right",
        "angles-left": "fas fa-angle-double-left",
        "angles-right": "fas fa-angle-double-right",
        "api": "fas fa-code",
        "arrow-left": "fas fa-arrow-left",
        "arrow-right": "fas fa-arrow-right",
        "arrow-up": "fas fa-arrow-up",
        "arrow-down": "fas fa-arrow-down",
        "back": "fas fa-arrow-left",
        "browse": "fas fa-book-open-reader",
        "cancel": "fas fa-times",
        "chart": "fas fa-chart-bar",
        "close": "fas fa-times",
        "circle-half": "fas fa-circle-half-stroke",
        "comments": "fas fa-comments",
        "community": "fas fa-users",
        "contributors": "fas fa-user-friends",
        "dashboard": "dashboard.svg",
        "dataset": "fas fa-folder",
        "delete": "fas fa-trash",
        "documentation": "fas fa-book",
        "download": "fas fa-download",
        "download-zip": "fas fa-file-zipper",
        "download-xml": "filetype-xml.svg",
        "edit": "fas fa-edit",
        "email": "fas fa-envelope",
        "expand": "fas fa-expand",
        "export": "fas fa-file-export",
        "ellipsis": "fas fa-ellipsis-v",
        # "facebook": "facebook.svg",
        "filter": "fas fa-filter",
        "github": "fab fa-github",
        "globe": "fas fa-globe",
        "grid": "grid.svg",
        "home": "fas fa-home",
        "identifier": "fas fa-fingerprint",
        "image": "fas fa-image",
        "images": "fas fa-images",
        "import": "fas fa-file-arrow-up",
        "info": "fas fa-info-circle",
        "invite": "fas fa-envelope",
        "linkedin": "fab fa-linkedin",
        "literature": "fas fa-book",
        "login": "fas fa-sign-in-alt",
        "logout": "fas fa-sign-out-alt",
        "location": "fas fa-map-marker-alt",
        "lock": "fas fa-lock",
        "manage_account": "fas fa-user-cog",
        "map": "fas fa-map-marked-alt",
        "measurement": "fas fa-ruler",
        "measurements": "fas fa-ruler-combined",
        "menu": "fas fa-bars",
        "missing_image": "missing_image.svg",
        "moon": "fas fa-moon",
        "orcid": "orcid/authenticated.svg",
        "orcid_unauthenticated": "orcid/unauthenticated.svg",
        "ORCID": "orcid/authenticated.svg",
        "organisation": "fas fa-building",
        "organization": "fas fa-building",
        "organization_svg": "organization.svg",
        "overview": "fas fa-book-open",
        "person": "user.svg",
        "plus": "fas fa-plus",
        "preferences": "fas fa-sliders",
        "project": "fas fa-layer-group",
        "ror": "ror.svg",
        "ROR": "ror.svg",
        "rotate": "fas fa-sync-alt",
        "sample": "fas fa-database",
        "save": "fas fa-save",
        "search": "fas fa-search",
        "send": "fas fa-paper-plane",
        "share": "fas fa-share",
        "spinner": "spinner.svg",
        "star-outline": "far fa-star",
        "star-solid": "fas fa-star",
        "sun": "fas fa-sun",
        "table": "fas fa-table",
        # "upload": "fas fa-upload",
        "upload": "fas fa-cloud-arrow-up",
        "user-circle": "fas fa-user-circle",
        "user": "fas fa-user",
        "user_svg": "user.svg",
        "vocabularies": "fas fa-book-open",
        "whatsapp": "fab fa-whatsapp",
        "x_twitter": "fab fa-x-twitter",
        # django-account-management
        "password_change": "fas fa-key",
        "mfa": "fas fa-lock",
        "link": "fas fa-link",
        "gear": "fas fa-cog",
        "sessions": "fas fa-user-clock",
        "site_admin": "fas fa-user-cog",
    },
}
