EASY_ICONS = {
    "default": {
        "renderer": "easy_icons.renderers.ProviderRenderer",
        "config": {
            "tag": "i",
        },
        "icons": {
            "administration": "fas fa-toolbox",
            "account_center": "fas fa-shield-halved",
            "angle-left": "fas fa-angle-left",
            "angle-right": "fas fa-angle-right",
            "angles-left": "fas fa-angle-double-left",
            "angles-right": "fas fa-angle-double-right",
            "api": "fas fa-code",
            "arrow-left": "fas fa-arrow-left",
            "arrow-right": "fas fa-arrow-right",
            "arrow-up": "fas fa-arrow-up",
            "arrow-down": "fas fa-arrow-down",
            "book": "fas fa-book",
            "back": "fas fa-arrow-left",
            "browse": "fas fa-book-open-reader",
            "cancel": "fas fa-times",
            "chart": "fas fa-chart-bar",
            "close": "fas fa-times",
            "circle-half": "fas fa-circle-half-stroke",
            "check_circle": "fas fa-check-circle",
            "community": "fas fa-users",
            "contributors": "fas fa-user-friends",
            "dataset": "fas fa-folder",
            "delete": "fas fa-trash",
            "documentation": "fas fa-book",
            "download": "fas fa-download",
            "download-zip": "fas fa-file-zipper",
            "edit": "fas fa-edit",
            "email": "fas fa-envelope",
            "expand": "fas fa-expand",
            "export": "fas fa-file-export",
            "ellipsis": "fas fa-ellipsis-v",
            # "facebook": "facebook.svg",
            "filter": "fas fa-filter",
            "github": "fab fa-github",
            "globe": "fas fa-globe",
            "home": "fas fa-home",
            "identifier": "fas fa-fingerprint",
            "image": "fas fa-image",
            "images": "fas fa-images",
            "import": "fas fa-file-arrow-up",
            "info": "fas fa-info-circle",
            "invite": "fas fa-envelope",
            "linkedin": "fab fa-linkedin",
            "literature": "fas fa-book",
            "login": "fas fa-sign-in-alt",
            "logout": "fas fa-sign-out-alt",
            "location": "fas fa-map-marker-alt",
            "lock": "fas fa-lock",
            "manage_account": "fas fa-user-cog",
            "map": "fas fa-map-marked-alt",
            "measurement": "fas fa-ruler",
            "measurements": "fas fa-ruler-combined",
            "menu": "fas fa-bars",
            "moon": "fas fa-moon",
            "organisation": "fas fa-building",
            "organization": "fas fa-building",
            "overview": "fas fa-book-open",
            "plus": "fas fa-plus",
            "preferences": "fas fa-sliders",
            "project": "fas fa-layer-group",
            "rotate": "fas fa-sync-alt",
            "sample": "fas fa-database",
            "save": "fas fa-save",
            "search": "fas fa-search",
            "send": "fas fa-paper-plane",
            "share": "fas fa-share",
            "star-outline": "far fa-star",
            "star-solid": "fas fa-star",
            "sun": "fas fa-sun",
            "table": "fas fa-table",
            # "upload": "fas fa-upload",
            "upload": "fas fa-cloud-arrow-up",
            "user-circle": "fas fa-user-circle",
            "user": "fas fa-user",
            "vocabularies": "fas fa-book-open",
            "whatsapp": "fab fa-whatsapp",
            "x_twitter": "fab fa-x-twitter",
            # django-account-management
            "password_change": "fas fa-key",
            "mfa": "fas fa-lock",
            "link": "fas fa-link",
            "gear": "fas fa-cog",
            "sessions": "fas fa-user-clock",
            "site_admin": "fas fa-user-cog",
        },
    },
    "svg": {
        "renderer": "easy_icons.renderers.SvgRenderer",
        "config": {
            "svg_dir": "icons",
            "default_attrs": {
                "height": "1em",
                "fill": "currentColor",
            },
        },
        "icons": {
            "activity": "activity.svg",
            "dashboard": "dashboard.svg",
            "download-xml": "filetype-xml.svg",
            "grid": "grid.svg",
            "missing_image": "missing_image.svg",
            "orcid": "orcid/authenticated.svg",
            "orcid_unauthenticated": "orcid/unauthenticated.svg",
            "ORCID": "orcid/authenticated.svg",
            "organization_svg": "organization.svg",
            "person": "user.svg",
            "spinner": "spinner.svg",
            "ror": "ror.svg",
            "user_svg": "user.svg",
            "ROR": "ror.svg",
        },
    },
}
