EASY_ICONS = {
    "default": {
        "renderer": "easy_icons.renderers.ProviderRenderer",
        "config": {
            "tag": "i",
        },
        "icons": {
            # Core Actions
            "add": "bi bi-plus-circle",
            "create": "bi bi-plus-circle",
            "edit": "bi bi-pencil",
            "update": "bi bi-pencil-square",
            "delete": "bi bi-trash",
            "remove": "bi bi-trash",
            "save": "bi bi-floppy",
            "cancel": "bi bi-x-circle",
            "close": "bi bi-x",
            "confirm": "bi bi-check-circle",
            "view": "bi bi-eye",
            "hide": "bi bi-eye-slash",
            "share": "bi bi-share",
            # Navigation
            "menu": "bi bi-list",
            "menu_vertical": "bi bi-three-dots-vertical",
            "menu_horizontal": "bi bi-three-dots",
            "chevron_left": "bi bi-chevron-left",
            "chevron_right": "bi bi-chevron-right",
            "chevron_up": "bi bi-chevron-up",
            "chevron_down": "bi bi-chevron-down",
            "chevron_expand": "bi bi-chevron-expand",
            "arrow_left": "bi bi-arrow-left",
            "arrow_right": "bi bi-arrow-right",
            "arrow_up": "bi bi-arrow-up",
            "arrow_down": "bi bi-arrow-down",
            "external_link": "bi bi-box-arrow-up-right",
            # Search & Filter
            "search": "bi bi-search",
            "filter": "bi bi-funnel",
            "filter_active": "bi bi-funnel-fill",
            "sort": "bi bi-sort-down",
            "funding": "bi bi-cash-coin",
            # Data & Content Types
            "project": "bi bi-layers",
            "dataset": "bi bi-folder",
            "sample": "bi bi-droplet",
            "measurement": "bi bi-rulers",
            "table": "bi bi-table",
            "data": "bi bi-table",
            "chart": "bi bi-bar-chart",
            "analytics": "bi bi-graph-up",
            "activity": "bi bi-activity",
            "timeline": "bi bi-clock-history",
            # Charts & Visualization
            "bar-chart": "bi bi-bar-chart",
            "line-chart": "bi bi-graph-up",
            "pie-chart": "bi bi-pie-chart",
            "scatter-plot": "bi bi-broadcast",
            "heatmap": "bi bi-grid-3x3-gap",
            "histogram": "bi bi-bar-chart-steps",
            # File Operations
            "download": "bi bi-download",
            "upload": "bi bi-upload",
            "import": "bi bi-box-arrow-in-down",
            "export": "bi bi-box-arrow-up",
            "file": "bi bi-file-earmark",
            "file_text": "bi bi-file_text",
            # People & Organizations
            "person": "bi bi-person",
            "people": "bi bi-people",
            "organization": "bi bi-building",
            # Location & Geography
            "location": "bi bi-geo-alt",
            "map": "bi bi-map",
            "globe": "bi bi-globe",
            # Metadata & Info
            "info": "bi bi-info-circle",
            "help": "bi bi-question-circle",
            "documentation": "bi bi-book",
            "literature": "bi bi-journal-text",
            "description": "bi bi-file-text",
            "keywords": "bi bi-tags",
            "tag": "bi bi-tag",
            "calendar": "bi bi-calendar3",
            "date": "bi bi-calendar3",
            "time": "bi bi-clock",
            "identifier": "bi bi-fingerprint",
            "link": "bi bi-link-45deg",
            "relationships": "bi bi-diagram-3",
            # Settings & Configuration
            "settings": "bi bi-gear",
            "preferences": "bi bi-sliders",
            "administration": "bi bi-tools",
            "permissions": "bi bi-shield-check",
            "verified": "bi bi-patch-check",
            # UI Elements
            "sidebar": "bi bi-layout-sidebar",
            "grid": "bi bi-grid",
            "list_view": "bi bi-list",
            "card_view": "bi bi-grid-3x2",
            "collapse": "bi bi-chevron-down",
            "expand": "bi bi-arrows-expand",
            # Media
            "image": "bi bi-image",
            "images": "bi bi-images",
            "rotate": "bi bi-arrow-clockwise",
            # Status & Indicators
            "success": "bi bi-check-circle",
            "error": "bi bi-x-circle",
            "warning": "bi bi-exclamation-triangle",
            "pending": "bi bi-clock",
            "loading": "bi bi-arrow-repeat",
            # Misc
            "home": "bi bi-house",
            "dashboard": "bi bi-speedometer2",
            "email": "bi bi-envelope",
            "lock": "bi bi-lock",
            "unlock": "bi bi-unlock",
            "visible": "bi bi-eye",
            "private": "bi bi-eye-slash",
            "star": "bi bi-star",
            "star_filled": "bi bi-star-fill",
            "lightbulb": "bi bi-lightbulb",
            "box": "bi bi-box",
            "review": "bi bi-chat-square-text",
            "comment": "bi bi-chat",
            "statistics": "bi bi-bar-chart",
            "award": "bi bi-award",
            "cloud_check": "bi bi-cloud-check",
            "cloud-check": "bi bi-cloud-check",
            "database_fill": "bi bi-database-fill",
            "database-fill": "bi bi-database-fill",
            # Theme
            "theme_light": "bi bi-sun",
            "theme_dark": "bi bi-moon",
            "theme_auto": "bi bi-circle-half",
            # Social & External
            "github": "bi bi-github",
            "linkedin": "bi bi-linkedin",
            "whatsapp": "bi bi-whatsapp",
            "x_twitter": "bi bi-twitter-x",
            # Auth
            "login": "bi bi-box-arrow-in-right",
            "logout": "bi bi-box-arrow-right",
            "password": "bi bi-key",
            "mfa": "bi bi-shield-lock",
            "account": "bi bi-person-circle",
            "sessions": "bi bi-clock-history",
        },
    },
    "svg": {
        "renderer": "easy_icons.renderers.SvgRenderer",
        "config": {
            "svg_dir": "icons",
            "default_attrs": {
                "height": "1em",
                "fill": "currentColor",
            },
        },
        "icons": {
            "activity": "activity.svg",
            "dashboard": "dashboard.svg",
            "download-xml": "filetype-xml.svg",
            "grid": "grid.svg",
            "missing_image": "missing_image.svg",
            "orcid": "orcid/authenticated.svg",
            "orcid_unauthenticated": "orcid/unauthenticated.svg",
            "ORCID": "orcid/authenticated.svg",
            "organization_svg": "organization.svg",
            "person": "user.svg",
            "spinner": "spinner.svg",
            "ror": "ror.svg",
            "user_svg": "user.svg",
            "ROR": "ror.svg",
        },
    },
}
