"""Test admin inheritance validation in registry configuration."""

import pytest
from django.contrib import admin

from fairdm.core.sample.admin import SampleChildAdmin
from fairdm.registry.config import ModelConfiguration
from fairdm.registry.exceptions import ConfigurationError
from fairdm_demo.models import RockSample


class TestAdminInheritanceValidation:
    """Test that registry validates admin class inheritance for polymorphic models."""

    def test_sample_with_wrong_admin_class_raises_error(self):
        """Sample subclass with admin not inheriting from SampleChildAdmin should raise error."""

        class WrongAdmin(admin.ModelAdmin):
            """Wrong admin class - doesn't inherit from SampleChildAdmin."""

            pass

        with pytest.raises(ConfigurationError) as exc_info:
            ModelConfiguration(
                model=RockSample,
                admin_class=WrongAdmin,
                fields=["name", "rock_type"],
            )

        assert "must inherit from SampleChildAdmin" in str(exc_info.value)
        assert "RockSample" in str(exc_info.value)
        assert "WrongAdmin" in str(exc_info.value)

    def test_sample_with_correct_admin_class_passes(self):
        """Sample subclass with admin inheriting from SampleChildAdmin should pass."""

        class CorrectAdmin(SampleChildAdmin):
            """Correct admin class - inherits from SampleChildAdmin."""

            base_model = RockSample
            show_in_index = True

        config = ModelConfiguration(
            model=RockSample,
            admin_class=CorrectAdmin,
            fields=["name", "rock_type"],
        )

        assert config.admin == CorrectAdmin

    def test_sample_without_admin_class_passes(self):
        """Sample subclass without admin_class should pass (auto-generates)."""
        config = ModelConfiguration(
            model=RockSample,
            fields=["name", "rock_type"],
        )

        # Should auto-generate an admin class
        assert config.admin is not None
        assert issubclass(config.admin, admin.ModelAdmin)

    def test_autogenerated_sample_admin_inherits_from_child_admin(self):
        """Auto-generated Sample admin should inherit from SampleChildAdmin."""
        config = ModelConfiguration(
            model=RockSample,
            fields=["name", "rock_type"],
        )

        # Auto-generated admin should use SampleChildAdmin as base
        admin_class = config.admin
        assert issubclass(admin_class, SampleChildAdmin), (
            f"Auto-generated admin for {RockSample.__name__} should inherit from SampleChildAdmin, "
            f"but got bases: {admin_class.__bases__}"
        )

        # Should have required polymorphic attributes
        assert hasattr(admin_class, "base_model")
        assert admin_class.base_model == RockSample
        assert hasattr(admin_class, "show_in_index")
        assert admin_class.show_in_index is True

    def test_measurement_with_wrong_admin_class_raises_error(self):
        """Measurement subclass with wrong admin should raise error."""
        from django.db import models

        from fairdm.core.models import Measurement

        # Create a simple Measurement subclass for testing
        class TestMeasurement(Measurement):
            """Test measurement model."""

            value = models.FloatField()

            class Meta:
                app_label = "fairdm_demo"

        class WrongMeasurementAdmin(admin.ModelAdmin):
            """Wrong admin class - doesn't inherit from MeasurementAdmin."""

            pass

        with pytest.raises(ConfigurationError) as exc_info:
            ModelConfiguration(
                model=TestMeasurement,
                admin_class=WrongMeasurementAdmin,
                fields=["value"],
            )

        assert "must inherit from MeasurementAdmin" in str(exc_info.value)
        assert "TestMeasurement" in str(exc_info.value)

    def test_measurement_with_correct_admin_class_passes(self):
        """Measurement subclass with correct admin should pass."""
        from django.db import models

        from fairdm.core.admin import MeasurementAdmin as MeasurementChildAdmin
        from fairdm.core.models import Measurement

        # Create a simple Measurement subclass for testing
        class TestMeasurement2(Measurement):
            """Test measurement model."""

            value = models.FloatField()

            class Meta:
                app_label = "fairdm_demo"

        class CorrectMeasurementAdmin(MeasurementChildAdmin):
            """Correct admin class - inherits from MeasurementAdmin."""

            base_model = TestMeasurement2
            show_in_index = True

        config = ModelConfiguration(
            model=TestMeasurement2,
            admin_class=CorrectMeasurementAdmin,
            fields=["value"],
        )

        assert config.admin == CorrectMeasurementAdmin

    def test_autogenerated_measurement_admin_inherits_from_child_admin(self):
        """Auto-generated Measurement admin should inherit from MeasurementAdmin."""
        from django.db import models

        from fairdm.core.admin import MeasurementAdmin as MeasurementChildAdmin
        from fairdm.core.models import Measurement

        # Create a simple Measurement subclass for testing
        class TestMeasurement3(Measurement):
            """Test measurement model."""

            value = models.FloatField()

            class Meta:
                app_label = "fairdm_demo"

        config = ModelConfiguration(
            model=TestMeasurement3,
            fields=["value"],
        )

        # Auto-generated admin should use MeasurementAdmin as base
        admin_class = config.admin
        assert issubclass(admin_class, MeasurementChildAdmin), (
            f"Auto-generated admin for {TestMeasurement3.__name__} should inherit from MeasurementAdmin, "
            f"but got bases: {admin_class.__bases__}"
        )

        # Should have required polymorphic attributes
        assert hasattr(admin_class, "base_model")
        assert admin_class.base_model == TestMeasurement3
        assert hasattr(admin_class, "show_in_index")
        assert admin_class.show_in_index is True

    def test_admin_class_as_string_reference(self):
        """Admin class can be provided as string reference."""
        from fairdm_demo.models import WaterSample

        config = ModelConfiguration(
            model=WaterSample,
            admin_class="fairdm_demo.admin.WaterSampleAdmin",
            fields=["name", "ph_level"],
        )

        # Should resolve string reference and validate
        from fairdm_demo.admin import WaterSampleAdmin

        assert config.admin == WaterSampleAdmin
