# Generated by Django 5.1.6 on 2025-05-21 13:35

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("generic", "0001_initial"),
        ("measurement", "0001_initial"),
        ("sample", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="sample",
            field=models.ForeignKey(
                help_text="The sample on which the measurement was made.",
                on_delete=django.db.models.deletion.PROTECT,
                to="sample.sample",
                verbose_name="sample",
            ),
        ),
        migrations.AddField(
            model_name="measurement",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="generic.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="measurementdate",
            name="related",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="measurement.measurement",
            ),
        ),
        migrations.AddField(
            model_name="measurementdescription",
            name="related",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="measurement.measurement",
            ),
        ),
        migrations.AddField(
            model_name="measurementidentifier",
            name="related",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="measurement.measurement",
            ),
        ),
    ]
