# Generated by Django 5.1.6 on 2025-06-27 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("measurement", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measurement",
            options={
                "default_related_name": "measurements",
                "ordering": ["-modified"],
                "permissions": [
                    ("add_contributor", "Can add contributors"),
                    ("modify_contributor", "Can modify contributors"),
                    ("modify_metadata", "Can modify metadata"),
                ],
                "verbose_name": "measurement",
                "verbose_name_plural": "measurements",
            },
        ),
    ]
