# Generated by Django 5.2.5 on 2025-11-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measurement", "0004_cleanup_duplicate_types"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="measurementdate",
            constraint=models.UniqueConstraint(
                fields=("related", "type"), name="measurementdate_unique_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="measurementdescription",
            constraint=models.UniqueConstraint(
                fields=("related", "type"), name="measurementdescription_unique_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="measurementidentifier",
            constraint=models.UniqueConstraint(
                fields=("related", "type"), name="measurementidentifier_unique_type"
            ),
        ),
    ]
