# Generated by Django 5.2.10 on 2026-02-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measurement", "0005_add_unique_type_constraints"),
        ("research_vocabs", "0002_alter_concept_unique_together"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="measurementdate",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="measurementdescription",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="measurementidentifier",
            managers=[],
        ),
        migrations.AlterField(
            model_name="measurement",
            name="keywords",
            field=models.ManyToManyField(
                blank=True,
                help_text="Controlled keywords for discoverability",
                to="research_vocabs.concept",
                verbose_name="keywords",
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="name",
            field=models.CharField(max_length=300, verbose_name="name"),
        ),
    ]
