# Generated by Django 5.2.11 on 2026-02-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measurement", "0006_alter_measurementdate_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurementdate",
            name="type",
            field=models.CharField(
                choices=[("Setup", "Setup date"), ("TearDown", "Tear down date")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="measurementdescription",
            name="type",
            field=models.CharField(
                choices=[
                    ("MeasurementConditions", "Conditions"),
                    ("MeasurementSetup", "Preparation"),
                    ("MeasurementTearDown", "Tear Down"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
