# Generated by Django 5.2.12 on 2026-04-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measurement", "0007_alter_measurementdate_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="local_id",
            field=models.CharField(
                blank=True,
                help_text="An alphanumeric identifier used by the creator/s to identify this measurement within the context of a specific dataset",
                max_length=255,
                null=True,
                verbose_name="Local ID",
            ),
        ),
    ]
