# Generated by Django 5.2.16 on 2026-08-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0008_measurement_local_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementidentifier',
            name='type',
            field=models.CharField(choices=[('DOI', 'DOI')], max_length=50),
        ),
    ]
