# Generated by Django 5.2.16 on 2026-08-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0009_alter_measurementidentifier_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='local_id',
            field=models.CharField(blank=True, db_index=True, help_text='An alphanumeric identifier used by the creator/s to identify this measurement within the context of a specific dataset', max_length=255, null=True, verbose_name='Local ID'),
        ),
    ]
