# Generated by Django 5.2.16 on 2026-08-25 14:12

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0010_alter_measurement_local_id'),
        ('sample', '0008_migrate_sample_status_to_unknown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='sample',
            field=auto_prefetch.ForeignKey(help_text='The sample on which the measurement was made.', on_delete=django.db.models.deletion.RESTRICT, to='sample.sample', verbose_name='sample'),
        ),
    ]
