# Generated by Django 5.2.16 on 2026-09-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0011_alter_measurement_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='name',
            field=models.CharField(db_index=True, max_length=300, verbose_name='name'),
        ),
    ]
