# Generated by Django 5.2.17 on 2026-09-18 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0012_alter_measurement_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementdescription',
            name='value',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(20000)]),
        ),
    ]
