version: '3.7'
name: fairdm

volumes:
  postgres: {}
  letsencrypt:
  media: {}

services:
  fairdm:
    build:
      context: .
      dockerfile: ./compose/fairdm/Dockerfile
    image: ssjenny90/fairdm:latest
  fairdm-postgis:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    image: fairdm/postgis
  django: &django
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    # image: fairdm_local
    depends_on:
      - fairdm
      - postgres
      - redis
      # - minio
    volumes:
      - ./:/app:z
    env_file: stack.env
    ports:
      - 8000:8000
      - 5678:5678
    command: start-django
  postgres:
    image: fairdm/postgis
    depends_on:
      - fairdm-postgis
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file: stack.env
  redis:
    image: redis:6

  celeryworker:
    <<: *django
    # depends_on:
      # - django
    ports: []
    command: start-celeryworker
  # celerybeat:
  #   <<: *django
  #   ports: []
  #   command: start-celerybeat

  # flower:
  #   <<: *django
  #   ports:
  #     - "5555:5555"
  #   command: start-flower

  minio:
    image: quay.io/minio/minio:latest
    volumes:
      - media:/minio
    env_file: stack.env
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /minio

  # node:
  #   build:
  #     context: .
  #     dockerfile: ./compose/node/Dockerfile
  #   image: fairdm_node
  #   depends_on:
  #     - django
  #   volumes:
  #     - ./:/app:z
  #     - /app/node_modules
  #   command: npm run dev
  #   ports:
  #     - '3000:3000'
