# Generated by Django 5.2.5 on 2025-08-13 09:21

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("measurement", "0003_alter_measurement_options"),
        ("sample", "0002_alter_sample_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomParentSample",
            fields=[
                (
                    "sample_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="sample.sample",
                    ),
                ),
                (
                    "char_field",
                    models.CharField(
                        help_text="Enter a string of up to 200 characters.",
                        max_length=200,
                        verbose_name="Character Field",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rock Sample",
                "verbose_name_plural": "Rock Samples",
            },
            bases=("sample.sample",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CustomSample",
            fields=[
                (
                    "sample_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="sample.sample",
                    ),
                ),
                (
                    "char_field",
                    models.CharField(
                        blank=True,
                        help_text="Enter a string of up to 200 characters.",
                        max_length=200,
                        null=True,
                        verbose_name="Character Field",
                    ),
                ),
                (
                    "text_field",
                    models.TextField(
                        blank=True,
                        help_text="Enter a large amount of text.",
                        null=True,
                        verbose_name="Text Field",
                    ),
                ),
                (
                    "integer_field",
                    models.IntegerField(
                        blank=True,
                        help_text="Enter an integer.",
                        null=True,
                        verbose_name="Integer Field",
                    ),
                ),
                (
                    "big_integer_field",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Enter a large integer.",
                        null=True,
                        verbose_name="Big Integer Field",
                    ),
                ),
                (
                    "positive_integer_field",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Enter a positive integer.",
                        null=True,
                        verbose_name="Positive Integer Field",
                    ),
                ),
                (
                    "positive_small_integer_field",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Enter a small positive integer.",
                        null=True,
                        verbose_name="Positive Small Integer Field",
                    ),
                ),
                (
                    "small_integer_field",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="Enter a small integer.",
                        null=True,
                        verbose_name="Small Integer Field",
                    ),
                ),
                (
                    "boolean_field",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Select True or False.",
                        null=True,
                        verbose_name="Boolean Field",
                    ),
                ),
                (
                    "date_field",
                    models.DateField(
                        blank=True,
                        help_text="Select a date.",
                        null=True,
                        verbose_name="Date Field",
                    ),
                ),
                (
                    "date_time_field",
                    models.DateTimeField(
                        blank=True,
                        help_text="Select a date and time.",
                        null=True,
                        verbose_name="Date Time Field",
                    ),
                ),
                (
                    "time_field",
                    models.TimeField(
                        blank=True,
                        help_text="Select a time.",
                        null=True,
                        verbose_name="Time Field",
                    ),
                ),
                (
                    "decimal_field",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Enter a decimal number.",
                        max_digits=5,
                        null=True,
                        verbose_name="Decimal Field",
                    ),
                ),
                (
                    "float_field",
                    models.FloatField(
                        blank=True,
                        help_text="Enter a floating point number.",
                        null=True,
                        verbose_name="Float Field",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thin Section",
                "verbose_name_plural": "Thin Sections",
            },
            bases=("sample.sample",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ExampleMeasurement",
            fields=[
                (
                    "measurement_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="measurement.measurement",
                    ),
                ),
                (
                    "char_field",
                    models.CharField(
                        blank=True,
                        help_text="Enter a string of up to 200 characters.",
                        max_length=200,
                        null=True,
                        verbose_name="Character Field",
                    ),
                ),
                (
                    "text_field",
                    models.TextField(
                        blank=True,
                        help_text="Enter a large amount of text.",
                        null=True,
                        verbose_name="Text Field",
                    ),
                ),
                (
                    "integer_field",
                    models.IntegerField(
                        blank=True,
                        help_text="Enter an integer.",
                        null=True,
                        verbose_name="Integer Field",
                    ),
                ),
                (
                    "big_integer_field",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Enter a large integer.",
                        null=True,
                        verbose_name="Big Integer Field",
                    ),
                ),
                (
                    "positive_integer_field",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Enter a positive integer.",
                        null=True,
                        verbose_name="Positive Integer Field",
                    ),
                ),
                (
                    "positive_small_integer_field",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Enter a small positive integer.",
                        null=True,
                        verbose_name="Positive Small Integer Field",
                    ),
                ),
                (
                    "small_integer_field",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="Enter a small integer.",
                        null=True,
                        verbose_name="Small Integer Field",
                    ),
                ),
                (
                    "boolean_field",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Select True or False.",
                        null=True,
                        verbose_name="Boolean Field",
                    ),
                ),
                (
                    "date_field",
                    models.DateField(
                        blank=True,
                        help_text="Select a date.",
                        null=True,
                        verbose_name="Date Field",
                    ),
                ),
                (
                    "date_time_field",
                    models.DateTimeField(
                        blank=True,
                        help_text="Select a date and time.",
                        null=True,
                        verbose_name="Date Time Field",
                    ),
                ),
                (
                    "time_field",
                    models.TimeField(
                        blank=True,
                        help_text="Select a time.",
                        null=True,
                        verbose_name="Time Field",
                    ),
                ),
                (
                    "decimal_field",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Enter a decimal number.",
                        max_digits=5,
                        null=True,
                        verbose_name="Decimal Field",
                    ),
                ),
                (
                    "float_field",
                    models.FloatField(
                        blank=True,
                        help_text="Enter a floating point number.",
                        null=True,
                        verbose_name="Float Field",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("measurement.measurement",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
