# Generated by Django 5.2.12 on 2026-04-28 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fairdm_demo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customparentsample",
            options={},
        ),
    ]
