# Generated by Django 5.2.9 on 2026-01-13 12:18

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fairdm_demo", "0001_initial"),
        ("measurement", "0005_add_unique_type_constraints"),
        ("sample", "0004_add_unique_type_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="ICP_MS_Measurement",
            fields=[
                (
                    "measurement_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="measurement.measurement",
                    ),
                ),
                (
                    "isotope",
                    models.CharField(
                        help_text="Isotope notation (e.g., 207Pb, 206Pb, 238U)",
                        max_length=20,
                        verbose_name="Isotope",
                    ),
                ),
                (
                    "counts_per_second",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Raw instrument counts per second",
                        max_digits=15,
                        verbose_name="Counts per Second",
                    ),
                ),
                (
                    "concentration_ppb",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Calculated concentration in parts per billion",
                        max_digits=12,
                        null=True,
                        verbose_name="Concentration (ppb)",
                    ),
                ),
                (
                    "uncertainty_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Analytical uncertainty as percentage",
                        max_digits=5,
                        null=True,
                        verbose_name="Uncertainty (%)",
                    ),
                ),
                (
                    "dilution_factor",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Sample dilution factor applied",
                        max_digits=8,
                        verbose_name="Dilution Factor",
                    ),
                ),
                (
                    "internal_standard",
                    models.CharField(
                        blank=True,
                        help_text="Internal standard isotope used for drift correction",
                        max_length=20,
                        verbose_name="Internal Standard",
                    ),
                ),
                (
                    "analysis_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time of ICP-MS analysis",
                        null=True,
                        verbose_name="Analysis Date",
                    ),
                ),
            ],
            options={
                "verbose_name": "ICP-MS Measurement",
                "verbose_name_plural": "ICP-MS Measurements",
            },
            bases=("measurement.measurement",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="RockSample",
            fields=[
                (
                    "sample_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="sample.sample",
                    ),
                ),
                (
                    "rock_type",
                    models.CharField(
                        help_text="Type of rock (e.g., igneous, sedimentary, metamorphic)",
                        max_length=100,
                        verbose_name="Rock Type",
                    ),
                ),
                (
                    "mineral_content",
                    models.TextField(
                        blank=True,
                        help_text="Description of minerals present in the sample",
                        verbose_name="Mineral Content",
                    ),
                ),
                (
                    "weight_grams",
                    models.FloatField(
                        blank=True,
                        help_text="Sample weight in grams",
                        null=True,
                        verbose_name="Weight (grams)",
                    ),
                ),
                (
                    "collection_date",
                    models.DateField(
                        help_text="Date when sample was collected",
                        verbose_name="Collection Date",
                    ),
                ),
                (
                    "hardness_mohs",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Hardness on Mohs scale (1-10)",
                        max_digits=3,
                        null=True,
                        verbose_name="Mohs Hardness",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rock Sample",
                "verbose_name_plural": "Rock Samples",
            },
            bases=("sample.sample",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="SoilSample",
            fields=[
                (
                    "sample_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="sample.sample",
                    ),
                ),
                (
                    "soil_type",
                    models.CharField(
                        help_text="Classification of soil type",
                        max_length=50,
                        verbose_name="Soil Type",
                    ),
                ),
                (
                    "ph_level",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Soil pH (0-14 scale)",
                        max_digits=4,
                        verbose_name="pH Level",
                    ),
                ),
                (
                    "organic_matter_percent",
                    models.FloatField(
                        blank=True,
                        help_text="Percentage of organic matter",
                        null=True,
                        verbose_name="Organic Matter (%)",
                    ),
                ),
                (
                    "texture",
                    models.CharField(
                        blank=True,
                        help_text="Soil texture classification",
                        max_length=100,
                        verbose_name="Soil Texture",
                    ),
                ),
                (
                    "moisture_content",
                    models.FloatField(
                        blank=True,
                        help_text="Percentage of moisture",
                        null=True,
                        verbose_name="Moisture Content (%)",
                    ),
                ),
                (
                    "depth_cm",
                    models.IntegerField(
                        help_text="Sampling depth in centimeters",
                        verbose_name="Depth (cm)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soil Sample",
                "verbose_name_plural": "Soil Samples",
            },
            bases=("sample.sample",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="WaterSample",
            fields=[
                (
                    "sample_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="sample.sample",
                    ),
                ),
                (
                    "water_source",
                    models.CharField(
                        help_text="Source of water (river, lake, groundwater, etc.)",
                        max_length=100,
                        verbose_name="Water Source",
                    ),
                ),
                (
                    "temperature_celsius",
                    models.FloatField(
                        help_text="Water temperature in Celsius",
                        verbose_name="Temperature (°C)",
                    ),
                ),
                (
                    "ph_level",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Water pH (0-14 scale)",
                        max_digits=4,
                        verbose_name="pH Level",
                    ),
                ),
                (
                    "turbidity_ntu",
                    models.FloatField(
                        blank=True,
                        help_text="Turbidity in Nephelometric Turbidity Units",
                        null=True,
                        verbose_name="Turbidity (NTU)",
                    ),
                ),
                (
                    "dissolved_oxygen_mg_l",
                    models.FloatField(
                        blank=True,
                        help_text="Dissolved oxygen concentration",
                        null=True,
                        verbose_name="Dissolved Oxygen (mg/L)",
                    ),
                ),
                (
                    "conductivity_us_cm",
                    models.FloatField(
                        blank=True,
                        help_text="Electrical conductivity",
                        null=True,
                        verbose_name="Conductivity (μS/cm)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Water Sample",
                "verbose_name_plural": "Water Samples",
            },
            bases=("sample.sample",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="XRFMeasurement",
            fields=[
                (
                    "measurement_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="measurement.measurement",
                    ),
                ),
                (
                    "element",
                    models.CharField(
                        help_text="Chemical element symbol (e.g., Si, Al, Fe)",
                        max_length=10,
                        verbose_name="Element",
                    ),
                ),
                (
                    "concentration_ppm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Element concentration in parts per million",
                        max_digits=10,
                        verbose_name="Concentration (ppm)",
                    ),
                ),
                (
                    "detection_limit_ppm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Analytical detection limit in parts per million",
                        max_digits=10,
                        null=True,
                        verbose_name="Detection Limit (ppm)",
                    ),
                ),
                (
                    "instrument_model",
                    models.CharField(
                        blank=True,
                        help_text="XRF instrument model used for analysis",
                        max_length=100,
                        verbose_name="Instrument Model",
                    ),
                ),
                (
                    "measurement_conditions",
                    models.TextField(
                        blank=True,
                        help_text="Analytical conditions (voltage, current, atmosphere, etc.)",
                        verbose_name="Measurement Conditions",
                    ),
                ),
            ],
            options={
                "verbose_name": "XRF Measurement",
                "verbose_name_plural": "XRF Measurements",
            },
            bases=("measurement.measurement",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
