# Generated by Django 5.2.16 on 2026-08-19 14:10

import fairdm.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fairdm_demo', '0002_alter_customparentsample_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='icp_ms_measurement',
            name='uncertainty',
            field=fairdm.db.fields.DecimalQuantityField(base_units='microgram / liter', blank=True, decimal_places=3, help_text='The analytical uncertainty of the measured concentration, in the same units as the value.', max_digits=12, null=True, unit_choices=['microgram / liter'], verbose_name='Uncertainty'),
        ),
        migrations.AddField(
            model_name='icp_ms_measurement',
            name='value',
            field=fairdm.db.fields.DecimalQuantityField(base_units='microgram / liter', blank=True, decimal_places=3, help_text='The measured concentration, reported as a quantity carrying its own units.', max_digits=12, null=True, unit_choices=['microgram / liter'], verbose_name='Value'),
        ),
    ]
