# Generated by Django 5.1.6 on 2025-05-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Point",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified.",
                        verbose_name="Modified",
                    ),
                ),
                (
                    "x",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="The x-coordinate of the location.",
                        max_digits=8,
                        verbose_name="x",
                    ),
                ),
                (
                    "y",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="The y-coordinate of the location.",
                        max_digits=7,
                        verbose_name="y",
                    ),
                ),
                (
                    "crs",
                    models.CharField(
                        default="EPSG:4326",
                        editable=False,
                        help_text="The coordinate reference system.",
                        max_length=255,
                        verbose_name="CRS",
                    ),
                ),
            ],
            options={
                "verbose_name": "location",
                "verbose_name_plural": "locations",
                "unique_together": {("x", "y")},
            },
        ),
    ]
