# Generated by Django 5.2.9 on 2025-12-19 16:00

import django.db.models.deletion
import easy_thumbnails.fields
import fairdm.contrib.identity.models
import parler.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
        ("research_vocabs", "0002_alter_concept_unique_together"),
    ]

    operations = [
        # Step 1: Add new brand asset fields to Authority
        migrations.RemoveField(
            model_name="authority",
            name="icon",
        ),
        migrations.RemoveField(
            model_name="authority",
            name="logo",
        ),
        migrations.AddField(
            model_name="authority",
            name="icon_dark",
            field=easy_thumbnails.fields.ThumbnailerImageField(
                blank=True,
                help_text="Small icon/favicon for dark theme. ICO or PNG recommended.",
                null=True,
                upload_to=fairdm.contrib.identity.models.brand_asset_path,
                verbose_name="Icon (Dark Theme)",
            ),
        ),
        migrations.AddField(
            model_name="authority",
            name="icon_light",
            field=easy_thumbnails.fields.ThumbnailerImageField(
                blank=True,
                help_text="Small icon/favicon for light theme. ICO or PNG recommended.",
                null=True,
                upload_to=fairdm.contrib.identity.models.brand_asset_path,
                verbose_name="Icon (Light Theme)",
            ),
        ),
        migrations.AddField(
            model_name="authority",
            name="logo_dark",
            field=easy_thumbnails.fields.ThumbnailerImageField(
                blank=True,
                help_text="Logo displayed on dark backgrounds. SVG recommended.",
                null=True,
                upload_to=fairdm.contrib.identity.models.brand_asset_path,
                verbose_name="Logo (Dark Theme)",
            ),
        ),
        migrations.AddField(
            model_name="authority",
            name="logo_light",
            field=easy_thumbnails.fields.ThumbnailerImageField(
                blank=True,
                help_text="Logo displayed on light backgrounds. SVG recommended.",
                null=True,
                upload_to=fairdm.contrib.identity.models.brand_asset_path,
                verbose_name="Logo (Light Theme)",
            ),
        ),
        migrations.AlterField(
            model_name="authority",
            name="contact",
            field=models.EmailField(
                blank=True,
                help_text="Contact email for the governing authority.",
                max_length=254,
                null=True,
                verbose_name="Contact",
            ),
        ),
        migrations.AlterField(
            model_name="authority",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Website URL of the governing authority.",
                null=True,
                verbose_name="URL",
            ),
        ),
        
        # Step 2: Rename Database model to Identity
        migrations.RenameModel(
            old_name="Database",
            new_name="Identity",
        ),
        
        # Step 3: Remove old fields from Identity (formerly Database)
        migrations.RemoveField(
            model_name="identity",
            name="icon",
        ),
        migrations.RemoveField(
            model_name="identity",
            name="logo",
        ),
        
        # Step 4: Add new brand asset fields to Identity
        migrations.AddField(
            model_name="identity",
            name="icon_dark",
            field=easy_thumbnails.fields.ThumbnailerImageField(
                blank=True,
                help_text="Small icon/favicon for dark theme. ICO or PNG recommended.",
                null=True,
                upload_to=fairdm.contrib.identity.models.brand_asset_path,
                verbose_name="Icon (Dark Theme)",
            ),
        ),
        migrations.AddField(
            model_name="identity",
            name="icon_light",
            field=easy_thumbnails.fields.ThumbnailerImageField(
                blank=True,
                help_text="Small icon/favicon for light theme. ICO or PNG recommended.",
                null=True,
                upload_to=fairdm.contrib.identity.models.brand_asset_path,
                verbose_name="Icon (Light Theme)",
            ),
        ),
        migrations.AddField(
            model_name="identity",
            name="logo_dark",
            field=easy_thumbnails.fields.ThumbnailerImageField(
                blank=True,
                help_text="Logo displayed on dark backgrounds. SVG recommended.",
                null=True,
                upload_to=fairdm.contrib.identity.models.brand_asset_path,
                verbose_name="Logo (Dark Theme)",
            ),
        ),
        migrations.AddField(
            model_name="identity",
            name="logo_light",
            field=easy_thumbnails.fields.ThumbnailerImageField(
                blank=True,
                help_text="Logo displayed on light backgrounds. SVG recommended.",
                null=True,
                upload_to=fairdm.contrib.identity.models.brand_asset_path,
                verbose_name="Logo (Light Theme)",
            ),
        ),
        
        # Step 5: Update Identity meta and keywords field
        migrations.AlterModelOptions(
            name="identity",
            options={"verbose_name": "Portal Identity"},
        ),
        migrations.AlterField(
            model_name="identity",
            name="keywords",
            field=models.ManyToManyField(
                blank=True,
                help_text="A set of keywords from controlled vocabularies describing the portal.",
                to="research_vocabs.concept",
                verbose_name="Keywords",
            ),
        ),
    ]
