# Generated by Django 5.2.9 on 2025-12-19 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0002_rename_database_to_identity"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DatabaseTranslation",
            new_name="IdentityTranslation",
        ),
        migrations.AlterModelOptions(
            name="identitytranslation",
            options={
                "default_permissions": (),
                "managed": True,
                "verbose_name": "Portal Identity Translation",
            },
        ),
        migrations.AlterModelTable(
            name="identity",
            table="identity_database",
        ),
    ]
