# Generated by Django 5.2.17 on 2026-09-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_rename_databasetranslation_identitytranslation_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authoritytranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='identitytranslation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='authoritytranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='identity_authority_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='identitytranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='identity_database_translation_uniq_lang'),
        ),
    ]
