# Generated by Django 5.1.6 on 2025-07-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_alter_project_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectdescription",
            name="type",
            field=models.CharField(
                choices=[
                    ("Abstract", "Abstract"),
                    ("Introduction", "Introduction"),
                    ("Background", "Background"),
                    ("Objectives", "Objectives"),
                    ("ExpectedOutput", "Expected Output"),
                    ("Conclusions", "Conclusions"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
