# Generated by Django 5.2.5 on 2025-11-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_cleanup_duplicate_types"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="projectdate",
            constraint=models.UniqueConstraint(
                fields=("related", "type"), name="projectdate_unique_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectdescription",
            constraint=models.UniqueConstraint(
                fields=("related", "type"), name="projectdescription_unique_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectidentifier",
            constraint=models.UniqueConstraint(
                fields=("related", "type"), name="projectidentifier_unique_type"
            ),
        ),
    ]
