# Generated by Django 5.2.10 on 2026-02-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_add_unique_type_constraints"),
        ("research_vocabs", "0002_alter_concept_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "default_related_name": "projects",
                "ordering": ["-modified"],
                "permissions": [
                    ("add_contributor", "Can add contributors"),
                    ("modify_contributor", "Can modify contributors"),
                    ("modify_metadata", "Can modify metadata"),
                    ("change_project_metadata", "Can edit project metadata"),
                    ("change_project_settings", "Can change project settings"),
                ],
                "verbose_name": "project",
                "verbose_name_plural": "projects",
            },
        ),
        migrations.AlterModelOptions(
            name="projectdate",
            options={
                "default_related_name": "dates",
                "ordering": ["value"],
                "verbose_name": "project date",
                "verbose_name_plural": "project dates",
            },
        ),
        migrations.AlterModelOptions(
            name="projectdescription",
            options={
                "default_related_name": "descriptions",
                "verbose_name": "project description",
                "verbose_name_plural": "project descriptions",
            },
        ),
        migrations.AlterModelOptions(
            name="projectidentifier",
            options={
                "default_related_name": "identifiers",
                "verbose_name": "project identifier",
                "verbose_name_plural": "project identifiers",
            },
        ),
        migrations.AlterModelManagers(
            name="projectdate",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="projectdescription",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="projectidentifier",
            managers=[],
        ),
        migrations.AlterField(
            model_name="project",
            name="keywords",
            field=models.ManyToManyField(
                blank=True,
                help_text="Controlled keywords for discoverability",
                to="research_vocabs.concept",
                verbose_name="keywords",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=300, verbose_name="name"),
        ),
        migrations.AlterUniqueTogether(
            name="projectdescription",
            unique_together={("related", "type")},
        ),
    ]
