# Generated by Django 5.2.16 on 2026-08-17 23:44

import auto_prefetch
import django.db.models.deletion
import fairdm.core.project.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_project_options_alter_projectdate_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=auto_prefetch.ForeignKey(blank=True, editable=False, help_text="The user who created this project. Left unset if that user's account has since been removed.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding',
            field=models.JSONField(blank=True, help_text="Funding awards, in DataCite's funding reference shape: a list of objects, each naming a funder and optionally an award.", null=True, validators=[fairdm.core.project.validators.validate_funding], verbose_name='funding'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, 'Concept'), (1, 'Planning'), (2, 'In progress'), (3, 'Complete'), (4, 'Searching for collaborators')], default=0, help_text='The current lifecycle stage of the project.', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='projectidentifier',
            name='type',
            field=models.CharField(choices=[('DOI', 'DOI'), ('GRANT_NUMBER', 'Grant Number'), ('PROPOSAL_ID', 'Proposal Identifier')], max_length=50),
        ),
    ]
