# Generated by Django 5.2.16 on 2026-08-17 22:47

import auto_prefetch
import django.db.models.deletion
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_project_options_alter_projectdate_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=auto_prefetch.ForeignKey(blank=True, editable=False, help_text="The user who created this project. Left unset if that user's account has since been removed.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
    ]
