# Generated by Django 5.2.10 on 2026-01-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_alter_project_options_alter_projectdate_options_and_more"),
        ("research_vocabs", "0002_alter_concept_unique_together"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="projectdate",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="projectdescription",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="projectidentifier",
            managers=[],
        ),
        migrations.AlterField(
            model_name="project",
            name="keywords",
            field=models.ManyToManyField(
                blank=True,
                help_text="Controlled keywords for discoverability",
                to="research_vocabs.concept",
                verbose_name="keywords",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=300, verbose_name="name"),
        ),
    ]
