# Generated by Django 5.2.16 on 2026-08-17 22:55

import fairdm.core.project.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_project_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='funding',
            field=models.JSONField(blank=True, help_text="Funding awards, in DataCite's funding reference shape: a list of objects, each naming a funder and optionally an award.", null=True, validators=[fairdm.core.project.validators.validate_funding], verbose_name='funding'),
        ),
    ]
