# Generated by Django 5.2.16 on 2026-09-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_convert_funding_to_datacite_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(db_index=True, max_length=300, verbose_name='name'),
        ),
    ]
