# Generated by Django 5.2.16 on 2026-08-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_convert_funding_to_datacite_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, 'Concept'), (1, 'Planning'), (2, 'In progress'), (3, 'Complete'), (4, 'Searching for collaborators')], default=0, help_text='The current lifecycle stage of the project.', verbose_name='status'),
        ),
    ]
