# Generated by Django 5.2.17 on 2026-10-02 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dataset', '0014_alter_datasetdescription_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(help_text='The primary key of the record the message is about.', verbose_name='record id')),
                ('subject', models.CharField(choices=[('question', 'A general question'), ('early-access', 'Access to the data before it is published'), ('specimen', 'Borrowing a specimen')], default='question', help_text='What the message is about.', max_length=20, verbose_name='subject')),
                ('sent', models.DateTimeField(auto_now_add=True, help_text='When the message was sent.', verbose_name='sent')),
                ('content_type', models.ForeignKey(help_text='The type of the record the message is about.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='record type')),
                ('sender', models.ForeignKey(help_text='The person who wrote the message.', on_delete=django.db.models.deletion.CASCADE, related_name='contact_messages', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'verbose_name': 'contact message',
                'verbose_name_plural': 'contact messages',
                'ordering': ['-sent'],
            },
        ),
        migrations.CreateModel(
            name='ProblemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(help_text='The primary key of the record the report is about.', verbose_name='record id')),
                ('description', models.TextField(help_text='What is wrong, and where. Say what you expected to see if you know.', max_length=2000, verbose_name='description')),
                ('state', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', help_text='Whether the report is still open.', max_length=10, verbose_name='state')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the report was made.', verbose_name='reported')),
                ('resolved', models.DateTimeField(blank=True, help_text='When the report was marked resolved.', null=True, verbose_name='resolved')),
                ('note', models.TextField(blank=True, help_text='What was done about it. The person who reported the problem receives this by email.', max_length=1000, verbose_name='note to the reporter')),
                ('content_type', models.ForeignKey(help_text='The type of the record the report is about.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='record type')),
                ('dataset', models.ForeignKey(help_text='The dataset whose list of reported problems this report appears in.', on_delete=django.db.models.deletion.CASCADE, related_name='problem_reports', to='dataset.dataset', verbose_name='dataset')),
                ('reporter', models.ForeignKey(help_text='The reader who reported the problem.', on_delete=django.db.models.deletion.CASCADE, related_name='problem_reports', to=settings.AUTH_USER_MODEL, verbose_name='reporter')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Who marked the report resolved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_problem_reports', to=settings.AUTH_USER_MODEL, verbose_name='resolved by')),
            ],
            options={
                'verbose_name': 'reported problem',
                'verbose_name_plural': 'reported problems',
                'ordering': ['-created'],
            },
        ),
    ]
