# Generated by Django 5.1.3 on 2025-01-28 14:15

import django.db.models.deletion
import django.utils.timezone
import easy_thumbnails.fields
import fairdm.contrib.contributors.models
import fairdm.utils.models
import fairdm.utils.utils
import jsonfield_toolkit.models
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        editable=False,
                        length=22,
                        max_length=23,
                        prefix="c",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "image",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        blank=True,
                        null=True,
                        upload_to=fairdm.utils.utils.default_image_path,
                        verbose_name="profile image",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=512, verbose_name="preferred name"),
                ),
                (
                    "alternative_names",
                    jsonfield_toolkit.models.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        help_text="Any other names by which the contributor is known.",
                        null=True,
                        size=None,
                        verbose_name="alternative names",
                    ),
                ),
                (
                    "profile",
                    models.TextField(blank=True, null=True, verbose_name="profile"),
                ),
                (
                    "links",
                    jsonfield_toolkit.models.ArrayField(
                        base_field=models.URLField(),
                        blank=True,
                        default=list,
                        help_text="A list of online resources related to this contributor.",
                        null=True,
                        size=None,
                        verbose_name="links",
                    ),
                ),
                (
                    "lang",
                    jsonfield_toolkit.models.ArrayField(
                        base_field=models.CharField(max_length=5),
                        blank=True,
                        default=list,
                        help_text="Language of the contributor.",
                        null=True,
                        size=None,
                        verbose_name="language",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "contributor",
                "verbose_name_plural": "contributors",
                "ordering": ["name"],
            },
            bases=(fairdm.utils.models.PolymorphicMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ContributorRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vocab_name",
                    models.CharField(max_length=255, verbose_name="vocabulary"),
                ),
                ("uri", models.URLField(unique=True, verbose_name="URI")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "label",
                    models.CharField(max_length=255, verbose_name="preferred label"),
                ),
            ],
            options={
                "verbose_name": "role",
                "verbose_name_plural": "roles",
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "contributor_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="contributors.contributor",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("contributors.contributor", models.Model),
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "contributor_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="contributors.contributor",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="The city where the organization is based.",
                        max_length=255,
                        null=True,
                        verbose_name="city",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="The country where the organization is based.",
                        max_length=255,
                        null=True,
                        verbose_name="country",
                    ),
                ),
                (
                    "ror",
                    models.JSONField(
                        blank=True,
                        help_text="A JSON object containing information about the organization from the ROR API.",
                        null=True,
                        verbose_name="Research Organization Registry",
                    ),
                ),
            ],
            options={
                "verbose_name": "organization",
                "verbose_name_plural": "organizations",
            },
            bases=("contributors.contributor",),
        ),
        migrations.CreateModel(
            name="ContributorIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CROSSREF_FUNDER_ID", "Crossref Funder ID"),
                            ("ISNI", "ISNI"),
                            ("ORCID", "ORCID iD"),
                            ("ROR", "ROR"),
                            ("RESEARCHER_ID", "ResearcherID"),
                            ("WIKIDATA", "Wikidata"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="identifier",
                    ),
                ),
                (
                    "related",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contributors.contributor",
                    ),
                ),
            ],
            options={
                "verbose_name": "identifier",
                "verbose_name_plural": "identifiers",
                "abstract": False,
                "default_related_name": "identifiers",
            },
        ),
        migrations.CreateModel(
            name="OrganizationMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (0, "Pending"),
                            (1, "Member"),
                            (2, "Admin"),
                            (3, "Owner"),
                        ],
                        default=1,
                        help_text="The type of membership that the person has with the organization",
                        verbose_name="type",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        help_text="The person that is a member of the organization.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="person",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="The organization that the person is a member of.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="contributors.organization",
                        verbose_name="organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "affiliation",
                "verbose_name_plural": "affiliations",
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="members",
            field=models.ManyToManyField(
                help_text="A list of personal contributors that are members of the organization.",
                related_name="affiliations",
                through="contributors.OrganizationMember",
                to=settings.AUTH_USER_MODEL,
                verbose_name="members",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization that this organization is a part of.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_organizations",
                to="contributors.organization",
                verbose_name="parent organization",
            ),
        ),
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                ("object_id", models.CharField(max_length=23)),
                (
                    "roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Assigned roles for this contributor.",
                        null=True,
                        verbose_name="roles",
                    ),
                ),
                (
                    "store",
                    models.JSONField(
                        default=dict,
                        help_text="A JSON representation of the contributor profile at the time of publication",
                        verbose_name="contributor",
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        default=fairdm.contrib.contributors.models.contributor_permissions_default,
                        help_text="A JSON representation of the contributor's permissions at the time of publication",
                        verbose_name="permissions",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "contributor",
                    models.ForeignKey(
                        help_text="The person or organisation that contributed to the project or dataset.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contributions",
                        to="contributors.contributor",
                        verbose_name="contributor",
                    ),
                ),
            ],
            options={
                "verbose_name": "contributor",
                "verbose_name_plural": "contributors",
                "ordering": ["object_id", "order"],
                "unique_together": {("content_type", "object_id", "contributor")},
            },
        ),
    ]
