# Generated by Django 5.1.6 on 2025-05-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="date_joined",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="date joined"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
