# Generated by Django 5.1.6 on 2025-07-01 06:48

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contributors", "0002_delete_member_remove_person_is_member_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True,
                help_text="The country where the organization is based.",
                max_length=2,
                null=True,
                verbose_name="country",
            ),
        ),
    ]
