# Generated by Django 5.1.6 on 2025-05-16 10:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributors", "0002_alter_person_date_joined_alter_person_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="added",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="The date and time this record was added to the database.",
                verbose_name="Date added",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="modified",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The date and time this record was last modified.",
                verbose_name="Last modified",
            ),
        ),
    ]
