# Generated by Django 5.1.6 on 2025-07-03 18:47

import auto_prefetch
import django.db.models.deletion
import easy_thumbnails.fields
import fairdm.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributors", "0003_alter_organization_country"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContributorRole",
        ),
        migrations.RemoveField(
            model_name="contribution",
            name="permissions",
        ),
        migrations.RemoveField(
            model_name="contribution",
            name="store",
        ),
        migrations.AddField(
            model_name="contribution",
            name="affiliation",
            field=auto_prefetch.ForeignKey(
                blank=True,
                help_text="The organization that the contributor is affiliated with for this contribution.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="contributors.organization",
                verbose_name="affiliation",
            ),
        ),
        migrations.AddField(
            model_name="contributor",
            name="weight",
            field=models.FloatField(
                default=1.0,
                editable=False,
                help_text="A weighting factor to determine sort order of contributors in public lists based on their contributions, completion of profile and linking of external identifiers.",
                verbose_name="weight",
            ),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="image",
            field=easy_thumbnails.fields.ThumbnailerImageField(
                blank=True,
                help_text="A profile image for the contributor. This is displayed in the contributor's profile.",
                null=True,
                upload_to=fairdm.utils.utils.default_image_path,
                verbose_name="profile image",
            ),
        ),
    ]
