# Generated by Django 5.1.6 on 2025-05-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributors", "0005_organization_lat_organization_lon"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmember",
            name="is_current",
            field=models.BooleanField(
                default=True,
                help_text="Denotes whether this is a current affiliation of the contributor.",
                verbose_name="is current",
            ),
        ),
        migrations.AddField(
            model_name="organizationmember",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="Denotes whether this is the primary affiliation of the contributor.",
                verbose_name="primary organization",
            ),
        ),
    ]
