# Generated by Django 5.1.6 on 2025-05-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributors", "0006_organizationmember_is_current_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="is_member",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user is an active member of the community or has been added by another process. ",
                verbose_name="member",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
