# Generated by Django 5.2.5 on 2025-11-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributors", "0006_cleanup_duplicate_types"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="contributoridentifier",
            constraint=models.UniqueConstraint(
                fields=("related", "type"), name="contributoridentifier_unique_type"
            ),
        ),
    ]
