# Generated by Django 5.1.6 on 2025-05-27 13:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributors", "0007_person_is_member_alter_person_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="member_since",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="member since"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date joined"
            ),
        ),
    ]
