# Generated by Django 5.2.5 on 2025-12-03 09:07

import fairdm.contrib.contributors.validators
import jsonfield_toolkit.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributors", "0008_migrate_to_location_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributor",
            name="lang",
            field=jsonfield_toolkit.models.ArrayField(
                base_field=models.CharField(
                    max_length=5,
                    validators=[
                        fairdm.contrib.contributors.validators.validate_iso_639_1_language_code
                    ],
                ),
                blank=True,
                default=list,
                error_messages={
                    "item_invalid": "Item %(nth)s in the array is invalid."
                },
                help_text="ISO 639-1 language codes (e.g., 'en', 'es', 'fr').",
                null=True,
                size=None,
                verbose_name="language",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organizationmember",
            unique_together={("person", "organization")},
        ),
    ]
