# Generated by Django 5.2.10 on 2026-02-09 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contributors", "0009_alter_contributor_lang_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="contributoridentifier",
            managers=[],
        ),
    ]
