# Generated by Django 5.2.11 on 2026-02-19 17:35

import auto_prefetch
import django.db.models.deletion
from django.db import migrations, models


def cleanup_guardian_permissions(apps, schema_editor):
    """
    Remove guardian UserObjectPermission and GroupObjectPermission rows for manage_organization.
    
    This permission is now derived via OrganizationPermissionBackend from Affiliation.type,
    so stored guardian rows are no longer needed.
    """
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    
    # Get Organization content type
    try:
        org_ct = ContentType.objects.get(app_label="contributors", model="organization")
    except ContentType.DoesNotExist:
        # No organizations exist yet, nothing to clean up
        return
    
    # Try to delete the Permission object (may not exist in fresh databases)
    Permission.objects.filter(
        content_type=org_ct,
        codename="manage_organization"
    ).delete()
    
    # Clean up guardian's UserObjectPermission if guardian is installed
    try:
        UserObjectPermission = apps.get_model("guardian", "UserObjectPermission")
        UserObjectPermission.objects.filter(
            permission__content_type=org_ct,
            permission__codename="manage_organization"
        ).delete()
    except LookupError:
        # Guardian not installed or UserObjectPermission model doesn't exist
        pass
    
    # Clean up guardian's GroupObjectPermission if guardian is installed
    try:
        GroupObjectPermission = apps.get_model("guardian", "GroupObjectPermission")
        GroupObjectPermission.objects.filter(
            permission__content_type=org_ct,
            permission__codename="manage_organization"
        ).delete()
    except LookupError:
        # Guardian not installed or GroupObjectPermission model doesn't exist
        pass


def reverse_cleanup(apps, schema_editor):
    """
    No-op reverse migration.
    
    We cannot recreate the guardian permission rows because we don't know
    which users should have them. Re-running the forward migration or
    having users create new OWNER affiliations will establish the correct state.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("contributors", "0016_make_is_claimed_non_nullable"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "verbose_name": "organization",
                "verbose_name_plural": "organizations",
            },
        ),
        migrations.RunPython(cleanup_guardian_permissions, reverse_cleanup),
        migrations.AlterField(
            model_name="affiliation",
            name="organization",
            field=auto_prefetch.ForeignKey(
                help_text="The organization that the person is a member of.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="affiliations",
                to="contributors.organization",
                verbose_name="organization",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="is_claimed",
            field=models.BooleanField(
                default=False,
                help_text="True if this person has claimed their account. False for ghost/invited profiles.",
                verbose_name="is claimed",
            ),
        ),
    ]
