# Generated by Django 5.2.12 on 2026-03-31 07:11

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
import django_lifecycle.mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0017_remove_manage_organization_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, help_text='The date and time this record was added to the database.', verbose_name='Date added')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date and time this record was last modified.', verbose_name='Last modified')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('method', models.CharField(choices=[('orcid', 'ORCID Social Login'), ('email', 'Email Verification'), ('token', 'Claim Token Link'), ('admin_merge', 'Admin-Initiated Merge'), ('admin_manual', 'Admin Manual Activation')], max_length=20, verbose_name='method')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('success', models.BooleanField(verbose_name='success')),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='failure reason')),
                ('details', models.JSONField(default=dict, verbose_name='details')),
                ('initiated_by', auto_prefetch.ForeignKey(blank=True, help_text='Admin who initiated the claim, if admin-driven.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_log_initiated', to=settings.AUTH_USER_MODEL, verbose_name='initiated by')),
                ('source_person', auto_prefetch.ForeignKey(help_text='The unclaimed Person being claimed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_log_as_source', to=settings.AUTH_USER_MODEL, verbose_name='source person')),
                ('target_person', auto_prefetch.ForeignKey(help_text='The resulting claimed Person.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_log_as_target', to=settings.AUTH_USER_MODEL, verbose_name='target person')),
            ],
            options={
                'verbose_name': 'claiming audit log',
                'verbose_name_plural': 'claiming audit logs',
                'ordering': ['-timestamp'],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
