# Generated by Django 5.2.16 on 2026-08-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0018_claiming_audit_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributoridentifier',
            name='type',
            field=models.CharField(choices=[('ORCID', 'ORCID iD'), ('RESEARCHER_ID', 'ResearcherID'), ('ROR', 'ROR'), ('WIKIDATA', 'Wikidata'), ('ISNI', 'ISNI'), ('CROSSREF_FUNDER_ID', 'Crossref Funder ID')], max_length=50),
        ),
    ]
