# Generated by Django 5.2.16 on 2026-08-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0019_alter_contributoridentifier_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributor',
            options={'default_related_name': 'contributors', 'ordering': ['name'], 'verbose_name': 'contributor', 'verbose_name_plural': 'contributors'},
        ),
    ]
