# Generated by Django 5.2.16 on 2026-08-23 17:34

import fairdm.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0020_contributors_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='end_date',
            field=fairdm.db.fields.PartialDateField(blank=True, help_text="When the affiliation ended. Leave blank for active affiliations. Setting an end date ends any rights the affiliation's type would otherwise confer, such as manage_organization for an owner.", null=True, verbose_name='end date'),
        ),
    ]
