# Generated by Django 5.2.16 on 2026-08-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0020_alter_contributor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='name',
            field=models.CharField(help_text='The name by which the contributor is publicly known.', max_length=512, verbose_name='preferred name'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='profile',
            field=models.TextField(blank=True, help_text='A free-text description of the contributor.', null=True, verbose_name='profile'),
        ),
    ]
