# Generated by Django 5.2.17 on 2026-10-06 12:31

import auto_prefetch
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0021_alter_affiliation_end_date_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Can view'), (2, 'Can edit'), (3, 'Can manage')], help_text='What the person may do on this record: view, edit or manage. Empty for an organization, which holds no access.', null=True, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='affiliation',
            field=auto_prefetch.ForeignKey(blank=True, help_text='The organization that the contributor is affiliated with for this contribution.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contributors.organization', verbose_name='affiliation'),
        ),
    ]
