# Generated by Django 5.2.16 on 2026-08-20 09:43

import fairdm.contrib.contributors.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0021_alter_contributor_name_alter_contributor_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='lang',
            field=models.JSONField(blank=True, default=list, help_text="ISO 639-1 language codes (e.g., 'en', 'es', 'fr').", null=True, validators=[fairdm.contrib.contributors.validators.validate_iso_639_1_language_codes], verbose_name='language'),
        ),
    ]
