# Generated by Django 5.2.17 on 2026-10-06 12:58

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0022_contribution_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='affiliation',
            field=auto_prefetch.ForeignKey(blank=True, help_text='The organization that the contributor is affiliated with for this contribution.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contributors.organization', verbose_name='affiliation'),
        ),
    ]
