# Generated by Django 5.2.16 on 2026-08-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0022_alter_contributor_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='The date and time this record was last modified.', verbose_name='Last modified'),
        ),
    ]
