# Generated by Django 5.2.16 on 2026-08-20 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0024_rename_privacy_settings_to_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='weight',
        ),
    ]
