# Generated by Django 5.2.16 on 2026-08-20 09:54

import auto_prefetch
import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('contributors', '0025_remove_contributor_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='content_type',
            field=auto_prefetch.ForeignKey(help_text='The type of object this contribution is attributed to.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='object_id',
            field=models.CharField(help_text='The id of the object this contribution is attributed to.', max_length=23, verbose_name='object id'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='uuid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, help_text="The contributor's public identifier.", length=22, max_length=23, prefix='c', unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='contributoridentifier',
            name='related',
            field=auto_prefetch.ForeignKey(help_text='The contributor this identifier belongs to.', on_delete=django.db.models.deletion.CASCADE, to='contributors.contributor', verbose_name='contributor'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, help_text="The person's email address. Null for an unclaimed profile created for attribution alone.", max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
