# Generated by Django 5.2.16 on 2026-08-20 12:31

import auto_prefetch
import django.db.models.deletion
import django.db.models.functions.text
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('contributors', '0026_alter_contribution_content_type_and_more'),
        ('research_vocabs', '0002_alter_concept_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliation',
            options={'default_related_name': 'affiliations', 'verbose_name': 'affiliation', 'verbose_name_plural': 'affiliations'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'default_related_name': 'organizations', 'verbose_name': 'organization', 'verbose_name_plural': 'organizations'},
        ),
        migrations.AlterUniqueTogether(
            name='affiliation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='contribution',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.CharField(blank=True, choices=[('education', 'Education'), ('funder', 'Funder'), ('healthcare', 'Healthcare'), ('company', 'Company'), ('archive', 'Archive'), ('nonprofit', 'Nonprofit'), ('government', 'Government'), ('facility', 'Facility'), ('other', 'Other')], db_index=True, help_text="The kind of institution this organization is, drawn from ROR's set of organization types.", max_length=32, null=True, verbose_name='organization type'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='type',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Member'), (2, 'Admin'), (3, 'Owner')], db_index=True, default=1, help_text='The verification state / role of the person within the organization.', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, db_index=True, help_text='The city where the organization is based.', max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=django_countries.fields.CountryField(blank=True, db_index=True, help_text='The country where the organization is based.', max_length=2, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='parent',
            field=auto_prefetch.ForeignKey(blank=True, help_text='The organization that this organization is a part of.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_organizations', to='contributors.organization', verbose_name='parent organization'),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_claimed',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this person has claimed their account. False for ghost/invited profiles. Indexed because the account-state filters and the administrative claim-status filter both read it (decisions.md D8, Article IX).', verbose_name='is claimed'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['content_type', 'object_id'], name='contribution_object_idx'),
        ),
        migrations.AddConstraint(
            model_name='affiliation',
            constraint=models.UniqueConstraint(fields=('person', 'organization'), name='unique_affiliation_person_organization'),
        ),
        migrations.AddConstraint(
            model_name='affiliation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('person',), name='unique_primary_affiliation_per_person'),
        ),
        migrations.AddConstraint(
            model_name='contribution',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'contributor'), name='unique_contribution_per_contributor_object', violation_error_message='This contributor is already credited on this object.'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email__isnull', False)), name='unique_person_email_ci', violation_error_message='A person with this email address already exists.'),
        ),
    ]
