# Generated by Django 5.1.6 on 2025-02-20 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fairdm_core", "0002_alter_dataset_tags_alter_measurement_tags_and_more"),
        ("fairdm_location", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="The location of the sample.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fairdm_location.point",
                verbose_name="location",
            ),
        ),
        migrations.AlterField(
            model_name="datasetdate",
            name="type",
            field=models.CharField(
                choices=[
                    ("Available", "Date Available"),
                    ("CollectionStart", "Collection Start Date"),
                    ("CollectionEnd", "Collection End Date"),
                    ("Submitted", "Submission Date"),
                    ("Published", "Publication Date"),
                    ("Withdrawn", "Withdrawal Date"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="SampleRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("child_of", "child of")],
                        max_length=255,
                        verbose_name="type",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_samples",
                        to="fairdm_core.sample",
                        verbose_name="source",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_to",
                        to="fairdm_core.sample",
                        verbose_name="target",
                    ),
                ),
            ],
        ),
    ]
