# Generated by Django 5.2.5 on 2025-11-10 12:05

from django.db import migrations


def cleanup_duplicate_types(apps, schema_editor):
    """Remove duplicate Description/Date/Identifier entries.
    
    For each (related, type) combination that has duplicates,
    keep the most recently modified entry and delete the rest.
    """
    SampleDescription = apps.get_model("sample", "SampleDescription")
    SampleDate = apps.get_model("sample", "SampleDate")
    SampleIdentifier = apps.get_model("sample", "SampleIdentifier")
    
    models_to_clean = [
        ("SampleDescription", SampleDescription),
        ("SampleDate", SampleDate),
        ("SampleIdentifier", SampleIdentifier),
    ]
    
    total_deleted = 0
    
    for model_name, model in models_to_clean:
        # Find all (related, type) combinations with duplicates
        from django.db.models import Count
        duplicates = (
            model.objects.values("related", "type")
            .annotate(count=Count("id"))
            .filter(count__gt=1)
        )
        
        for dup in duplicates:
            # Get all instances with this (related, type) combination
            instances = model.objects.filter(
                related_id=dup["related"],
                type=dup["type"],
            ).order_by("-modified")
            
            # Keep the first (most recent), delete the rest
            instances_to_delete = instances[1:]
            count = instances_to_delete.count()
            if count > 0:
                instances_to_delete.delete()
                total_deleted += count
                print(
                    f"  Deleted {count} duplicate {model_name} "
                    f"(related_id={dup['related']}, type={dup['type']})"
                )
    
    if total_deleted > 0:
        print(f"Total duplicates removed: {total_deleted}")
    else:
        print("No duplicates found - database is clean!")


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0002_alter_sample_options"),
    ]

    operations = [
        migrations.RunPython(cleanup_duplicate_types, migrations.RunPython.noop),
    ]
