# Generated by Django 5.2.5 on 2025-11-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0003_cleanup_duplicate_types"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="sampledate",
            constraint=models.UniqueConstraint(
                fields=("related", "type"), name="sampledate_unique_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="sampledescription",
            constraint=models.UniqueConstraint(
                fields=("related", "type"), name="sampledescription_unique_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="sampleidentifier",
            constraint=models.UniqueConstraint(
                fields=("related", "type"), name="sampleidentifier_unique_type"
            ),
        ),
    ]
