# Generated by Django 5.2.10 on 2026-01-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_vocabs", "0002_alter_concept_unique_together"),
        ("sample", "0004_add_unique_type_constraints"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="sampledate",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="sampledescription",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="sampleidentifier",
            managers=[],
        ),
        migrations.AlterField(
            model_name="sample",
            name="keywords",
            field=models.ManyToManyField(
                blank=True,
                help_text="Controlled keywords for discoverability",
                to="research_vocabs.concept",
                verbose_name="keywords",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="name",
            field=models.CharField(max_length=300, verbose_name="name"),
        ),
    ]
