# Generated by Django 5.2.10 on 2026-02-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_vocabs", "0002_alter_concept_unique_together"),
        ("sample", "0004_add_unique_type_constraints"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sample",
            options={
                "default_related_name": "samples",
                "ordering": ["added"],
                "permissions": [
                    ("add_contributor", "Can add contributors"),
                    ("modify_contributor", "Can modify contributors"),
                    ("modify_metadata", "Can modify metadata"),
                    ("import_data", "Can import sample data"),
                ],
                "verbose_name": "sample",
                "verbose_name_plural": "samples",
            },
        ),
        migrations.AlterModelOptions(
            name="samplerelation",
            options={
                "verbose_name": "sample relationship",
                "verbose_name_plural": "sample relationships",
            },
        ),
        migrations.AlterModelManagers(
            name="sampledate",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="sampledescription",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="sampleidentifier",
            managers=[],
        ),
        migrations.AddField(
            model_name="sample",
            name="related",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_from",
                through="sample.SampleRelation",
                to="sample.sample",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="keywords",
            field=models.ManyToManyField(
                blank=True,
                help_text="Controlled keywords for discoverability",
                to="research_vocabs.concept",
                verbose_name="keywords",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="name",
            field=models.CharField(max_length=300, verbose_name="name"),
        ),
        migrations.AlterUniqueTogether(
            name="samplerelation",
            unique_together={("source", "target", "type")},
        ),
    ]
