# Generated by Django 5.2.12 on 2026-04-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0005_alter_sample_options_alter_samplerelation_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="local_id",
            field=models.CharField(
                blank=True,
                help_text="An alphanumeric identifier used by the creator/s to identify the sample within the context of a specific dataset",
                max_length=255,
                null=True,
                verbose_name="Local ID",
            ),
        ),
    ]
