# Generated by Django 5.2.10 on 2026-02-06 17:30

import auto_prefetch
import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("sample", "0005_alter_sampledate_managers_and_more"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SampleTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=100,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "sample tag",
                "verbose_name_plural": "sample tags",
            },
        ),
        migrations.AddField(
            model_name="sample",
            name="related",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_from",
                through="sample.SampleRelation",
                to="sample.sample",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="keywords",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Keywords from controlled vocabularies for categorization",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="keywords",
            ),
        ),
        migrations.CreateModel(
            name="SampleTaggedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.IntegerField(db_index=True, verbose_name="object ID"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_tagged_items",
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
                (
                    "tag",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="sample.sampletag",
                    ),
                ),
            ],
            options={
                "verbose_name": "tagged sample",
                "verbose_name_plural": "tagged samples",
            },
        ),
        migrations.AlterField(
            model_name="sample",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Free-text tags for flexible categorization",
                through="sample.SampleTaggedItem",
                to="sample.SampleTag",
                verbose_name="tags",
            ),
        ),
        migrations.AddIndex(
            model_name="sampletaggeditem",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="sample_samp_content_5e5251_idx",
            ),
        ),
    ]
