# Generated by Django 5.2.10 on 2026-02-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0006_add_tagging_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sample",
            options={
                "default_related_name": "samples",
                "ordering": ["added"],
                "permissions": [
                    ("add_contributor", "Can add contributors"),
                    ("modify_contributor", "Can modify contributors"),
                    ("modify_metadata", "Can modify metadata"),
                    ("import_data", "Can import sample data"),
                ],
                "verbose_name": "sample",
                "verbose_name_plural": "samples",
            },
        ),
    ]
