# Generated by Django 5.2.16 on 2026-08-19 00:36

import fairdm.core.vocabularies
import research_vocabs.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0007_alter_sample_status_alter_sample_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=research_vocabs.fields.ConceptField(default='unknown', help_text='The current custody status of the physical specimen.', max_length=9, verbose_name='status', vocabulary=fairdm.core.vocabularies.FairDMSampleStatus),
        ),
    ]
