# Generated by Django 5.2.16 on 2026-09-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0008_migrate_sample_status_to_unknown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='name',
            field=models.CharField(db_index=True, max_length=300, verbose_name='name'),
        ),
    ]
