from __future__ import annotations

from typing import TYPE_CHECKING

from django.conf import settings
from django.core.signing import BadSignature, SignatureExpired, TimestampSigner

if TYPE_CHECKING:
    from fairdm.contrib.contributors.models import Person

_DEFAULT_MAX_AGE = 7 * 24 * 60 * 60  # 7 days in seconds
_DEFAULT_SALT = "fairdm.contributor.claim"


def _get_signer() -> TimestampSigner:
    salt = getattr(settings, "CLAIM_TOKEN_SALT", _DEFAULT_SALT)
    return TimestampSigner(salt=salt)


def _get_max_age() -> int:
    return getattr(settings, "CLAIM_TOKEN_MAX_AGE", _DEFAULT_MAX_AGE)


def generate_claim_token(person: "Person") -> str:
    """Generate a signed, time-stamped claim token for the given Person.

    The token encodes the Person PK plus a HMAC timestamp.  No database row
    is stored — validity is enforced cryptographically at claim time.

    Args:
        person: The Person instance to generate the token for.

    Returns:
        Signed token string (URL-safe).
    """
    signer = _get_signer()
    return signer.sign(str(person.pk))


def validate_claim_token(token_string: str) -> "Person | None":
    """Validate a claim token and return the associated unclaimed Person.

    Performs three checks in order:
    1. HMAC signature is valid (raises ClaimingError on tamper).
    2. Token age is within CLAIM_TOKEN_MAX_AGE (raises ClaimingError on expiry).
    3. The resolved Person still has is_claimed=False (raises ClaimingError if
       already claimed — implicit revocation).

    Args:
        token_string: The signed token string generated by generate_claim_token().

    Returns:
        The unclaimed Person instance, or None if the token resolves to a banned
        (is_active=False) Person.

    Raises:
        ClaimingError: On tamper, expiry, or already-claimed person.
    """
    from fairdm.contrib.contributors.exceptions import ClaimingError
    from fairdm.contrib.contributors.models import Person

    signer = _get_signer()
    max_age = _get_max_age()

    try:
        pk_str = signer.unsign(token_string, max_age=max_age)
    except SignatureExpired as exc:
        raise ClaimingError("Claim token has expired.") from exc
    except BadSignature as exc:
        raise ClaimingError("Claim token is invalid or has been tampered with.") from exc

    try:
        person = Person.objects.get(pk=pk_str)
    except Person.DoesNotExist:
        raise ClaimingError("No Person found for this claim token.")

    if person.is_claimed:
        raise ClaimingError("This profile has already been claimed.")

    return person
